services:

  loadbalancer:
    build:
      context: ./loadbalancer
      dockerfile: Dockerfile
    ports:
      - "8198:8198"
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  service2:
    build:
      dockerfile: service2/Dockerfile
    container_name: service2
    networks:
      - internal

  service1:
    build:
      dockerfile: service1/Dockerfile
    depends_on:
      - service2
    networks:
      - internal
    deploy:
      replicas: 3

networks:
  internal:
    driver: bridge
